src/main/java/org/tsd/tsdbot/tsdtv/model/FillerType.java
package org.tsd.tsdbot.tsdtv.model;

/**
* Created by Joe on 2/1/2015.
*/
public enum FillerType {
    bump            (".bumps", "Bumps"),
    commercial      (".commercials", "Commercials"),
    show_intro      (null, "Show Intro"),
    block_intro     (null, "Block Intro"),
    block_outro     (null, "Block Outro");

    private String scheduleId;
    private String displayString;

    FillerType(String scheduleId, String displayString) {
        this.scheduleId = scheduleId;
        this.displayString = displayString;
    }

    public String getDisplayString() {
        return displayString;
    }

    public static FillerType fromSchedule(String scheduleId) {
        for(FillerType ft : values()) {
            if(scheduleId.equals(ft.scheduleId))
                return ft;
        }
        return null;
    }
}

src/main/java/org/tsd/tsdbot/tsdtv/model/TSDTVEpisode.java
package org.tsd.tsdbot.tsdtv.model;

import org.tsd.tsdbot.util.TSDTVUtil;

import java.io.File;

public class TSDTVEpisode extends Streamable implements Comparable<TSDTVEpisode> {

    private TSDTVShow show;
    private int episodeNumber = -1;

    public TSDTVEpisode(File file, TSDTVShow show) {
        super(file);
        this.show = show;
        try {
            this.episodeNumber = TSDTVUtil.getEpisodeNumberFromFilename(file.getName());
        } catch (Exception e) {
            this.episodeNumber = -1;
        }
    }

    public TSDTVShow getShow() {
        return show;
    }

    @Override
    public int getEpisodeNumber() {
        return episodeNumber;
    }

    public String getRawName() {
        return file.getName();
    }

    public String getPrettyName() {
        return file.getName().replaceAll("_", " ");
    }

    @Override
    public boolean isBroadcastable() {
        return true;
    }

    @Override
    public String toString() {
        return show.getPrettyName() + ": " + getPrettyName();
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        TSDTVEpisode that = (TSDTVEpisode) o;

        if (episodeNumber != that.episodeNumber) return false;
        if (!show.equals(that.show)) return false;

        return true;
    }

    @Override
    public int hashCode() {
        int result = show.hashCode();
        result = 31 * result + episodeNumber;
        return result;
    }

    @Override
    public int compareTo(TSDTVEpisode o) {
        int i = Integer.compare(episodeNumber, o.getEpisodeNumber());
        return (i != 0) ? i : getRawName().compareToIgnoreCase(o.getRawName());
    }
}

src/main/java/org/tsd/tsdbot/servlets/StatusServlet.java
package org.tsd.tsdbot.servlets;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import org.tsd.tsdbot.stats.Stats;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.util.LinkedHashMap;
import java.util.Set;

/**
 * Created by Joe on 1/11/2015.
 */
@Singleton
public class StatusServlet extends HttpServlet {

    @Inject
    private Set<Stats> stats;

    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        LinkedHashMap<String, Object> report = new LinkedHashMap<>();
        for(Stats s : stats) {
            report.putAll(s.getReport());
        }
        req.setAttribute("stats", report);
        req.getRequestDispatcher("/status.jsp").forward(req, resp);
    }
}

src/main/java/org/tsd/tsdbot/servlets/filename/FilenameImageServlet.java
package org.tsd.tsdbot.servlets.filename;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import org.apache.commons.io.IOUtils;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.tsd.tsdbot.FilenameLibrary;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.ByteArrayInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.net.URLDecoder;

@Singleton
public class FilenameImageServlet extends HttpServlet {

    private static final Logger logger = LoggerFactory.getLogger(FilenameImageServlet.class);

    @Inject
    private FilenameLibrary filenameLibrary;

    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        String path = URLDecoder.decode(req.getPathInfo(), "UTF-8");
        logger.info("Fetching filename from path: {}", path);
        String filename = null;
        try{
            filename = path.split("/")[1];
            logger.info("Parsed filename {}", filename);
            byte[] data = filenameLibrary.getFile(filename);
            IOUtils.copy(new ByteArrayInputStream(data), resp.getOutputStream());
            resp.getOutputStream().close();
        } catch (FileNotFoundException fnfe) {
            logger.error("File not found, filename = " + filename, fnfe);
            resp.sendError(HttpServletResponse.SC_NOT_FOUND, "Could not find file with name " + filename);
        } catch (Exception e) {
            logger.error("Unknown error finding filename " + filename, e);
            resp.sendError(HttpServletResponse.SC_BAD_REQUEST, "Could not find filename due to unknown error: " + e.getMessage());
        }
    }
}

src/main/java/org/tsd/tsdbot/servlets/filename/FilenameListingServlet.java
package org.tsd.tsdbot.servlets.filename;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.tsd.tsdbot.FilenameLibrary;

import javax.inject.Named;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.File;
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.util.LinkedList;
import java.util.List;
import java.util.Random;

@Singleton
public class FilenameListingServlet extends HttpServlet {

    private static final Logger log = LoggerFactory.getLogger(FilenameListingServlet.class);

    @Inject
    private Random random;

    @Inject @Named("serverUrl")
    private String serverUrl;

    @Inject
    private FilenameLibrary filenameLibrary;

    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {

        List<EncodedFilename> encodedFilenames = new LinkedList<>();
        for(File f : filenameLibrary.readFiles()) {
            encodedFilenames.add(new EncodedFilename(f.getName()));
        }

        req.setAttribute("filenames", encodedFilenames);
        req.setAttribute("serverUrl", serverUrl);
        req.setAttribute("name", tsdNames[random.nextInt(tsdNames.length)]);
        req.getRequestDispatcher("/filenames.jsp").forward(req, resp);
    }

    public static class EncodedFilename {
        private String encoded;
        private String unencoded;

        public EncodedFilename(String unencoded) throws UnsupportedEncodingException {
            this.unencoded = unencoded;
            this.encoded = URLEncoder.encode(unencoded, "UTF-8");
        }

        public String getEncoded() {
            return encoded;
        }

        public String getUnencoded() {
            return unencoded;
        }
    }

    private static final String[] tsdNames = {
            "The Strong Dudes",
            "The Swole Dudes",
            "The Salty Dudes",
            "Two Stupid Dogs",
            "Tex's Stupid Dogs"
    };
}

src/main/java/org/tsd/tsdbot/servlets/filename/RandomFilenameImageServlet.java
package org.tsd.tsdbot.servlets.filename;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import org.apache.commons.io.IOUtils;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.tsd.tsdbot.FilenameLibrary;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.ByteArrayInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.net.URLDecoder;

@Singleton
public class RandomFilenameImageServlet extends HttpServlet {

    private static final Logger logger = LoggerFactory.getLogger(RandomFilenameImageServlet.class);

    @Inject
    private FilenameLibrary filenameLibrary;

    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        String path = URLDecoder.decode(req.getPathInfo(), "UTF-8");
        logger.info("Fetching random filename from path: {}", path);
        String filename = null;
        try{
            filename = path.split("/")[1];
            logger.info("Parsed random filename {}", filename);
            byte[] data = filenameLibrary.getRandomFilename(filename);
            IOUtils.copy(new ByteArrayInputStream(data), resp.getOutputStream());
            resp.getOutputStream().close();
        } catch (FileNotFoundException fnfe) {
            logger.error("File not found, filename = " + filename, fnfe);
            resp.sendError(HttpServletResponse.SC_NOT_FOUND, "Could not find file with name " + filename);
        } catch (Exception e) {
            logger.error("Unknown error finding filename " + filename, e);
            resp.sendError(HttpServletResponse.SC_BAD_REQUEST, "Could not find filename due to unknown error: " + e.getMessage());
        }
    }
}

src/main/java/org/tsd/tsdbot/servlets/hustle/HustleChartServlet.java
package org.tsd.tsdbot.servlets.hustle;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import org.jfree.chart.ChartUtilities;
import org.tsd.tsdbot.stats.HustleStats;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;

@Singleton
public class HustleChartServlet extends HttpServlet {

    @Inject
    private HustleStats hustleStats;

    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        resp.setContentType("image/png");
        if(hustleStats.getChart() != null)
            ChartUtilities.writeChartAsPNG(resp.getOutputStream(), hustleStats.getChart(), 1000, 600);
        resp.getOutputStream().close();
    }
}

src/main/java/org/tsd/tsdbot/servlets/hustle/HustleServlet.java
package org.tsd.tsdbot.servlets.hustle;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import org.tsd.tsdbot.stats.SystemStats;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;

/**
 * Created by Joe on 1/11/2015.
 */
@Singleton
public class HustleServlet extends HttpServlet {

    @Inject
    SystemStats systemStats;

    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        systemStats.getReport();
        req.getRequestDispatcher("/hustle.jsp").forward(req, resp);
    }
}

src/main/java/org/tsd/tsdbot/servlets/tsdtv/TSDTVAnalysisServlet.java
package org.tsd.tsdbot.servlets.tsdtv;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import org.apache.commons.lang3.StringUtils;
import org.apache.commons.lang3.time.DurationFormatUtils;
import org.tsd.tsdbot.tsdtv.TSDTVFileProcessor;
import org.tsd.tsdbot.tsdtv.processor.*;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.util.List;
import java.util.TreeSet;

/**
 * Created by Joe on 2/28/2015.
 */
@Singleton
public class TSDTVAnalysisServlet extends HttpServlet {

    @Inject
    private TSDTVFileProcessor fileProcessor;

    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        String analysisId = req.getPathInfo().split("/")[1];
        if(StringUtils.isEmpty(analysisId)) {
            resp.sendError(HttpServletResponse.SC_BAD_REQUEST, "Could not parse analysis id");
        } else {
            AnalysisCollection analyses = fileProcessor.getAnalysesForId(analysisId);
            if(analyses == null) {
                resp.sendError(HttpServletResponse.SC_NOT_FOUND, "Could not find analysis with id " + analysisId);
            } else if(analyses.getAnalyses().isEmpty()) {
                resp.sendError(HttpServletResponse.SC_NOT_FOUND, "Analysis for " + analyses.getFolder() + " is empty");
            } else {
                resp.getOutputStream().print(analyses.getTextOutput());
                resp.getOutputStream().close();
            }
        }
    }

}

src/main/java/org/tsd/tsdbot/servlets/tsdtv/TSDTVControlServlet.java
package org.tsd.tsdbot.servlets.tsdtv;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import org.tsd.tsdbot.tsdtv.NoStreamRunningException;
import org.tsd.tsdbot.tsdtv.TSDTV;
import org.tsd.tsdbot.tsdtv.TSDTVWebUser;
import org.tsd.tsdbot.util.ServletUtils;

import javax.naming.AuthenticationException;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.net.InetAddress;

@Singleton
public class TSDTVControlServlet extends HttpServlet {

    @Inject
    private TSDTV tsdtv;

    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {}

    @Override
    protected void doPost(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        try {
            InetAddress inetAddress = InetAddress.getByName(ServletUtils.getIpAddress(req));
            TSDTVWebUser tsdtvWebUser = new TSDTVWebUser(inetAddress);
            if(req.getParameter("type").equals("kill")) {
                tsdtv.kill(tsdtvWebUser);
            } else if (req.getParameter("type").equals("pause")) {
                switch (tsdtv.getState()) {
                    case running: {
                        tsdtv.pause(tsdtvWebUser);
                        break;
                    }
                    case paused: {
                        tsdtv.unpause(tsdtvWebUser);
                        break;
                    }
                    default:
                        throw new IllegalStateException("Trying to pause or unpause a " + tsdtv.getState() + " stream");
                }
            }
        } catch (NoStreamRunningException nsre) {
            resp.sendError(HttpServletResponse.SC_BAD_REQUEST, "There isn't a stream running");
        } catch (AuthenticationException ae) {
            resp.sendError(HttpServletResponse.SC_FORBIDDEN, "You don't have permission to perform that action");
        } catch (IllegalStateException ise) {
            resp.sendError(HttpServletResponse.SC_FORBIDDEN, ise.getMessage());
        }
    }
}

src/main/java/org/tsd/tsdbot/servlets/tsdtv/TSDTVPlayServlet.java
package org.tsd.tsdbot.servlets.tsdtv;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import org.tsd.tsdbot.tsdtv.*;
import org.tsd.tsdbot.tsdtv.model.TSDTVEpisode;
import org.tsd.tsdbot.util.ServletUtils;
import org.tsd.tsdbot.util.SurgeProtector;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.net.InetAddress;
import java.util.HashSet;
import java.util.Set;

@Singleton
public class TSDTVPlayServlet extends HttpServlet {

    @Inject
    private TSDTV tsdtv;

    @Inject
    private TSDTVLibrary library;

    private final Set<String> servletBlacklist = new HashSet<>();

    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {}

    @Override
    protected void doPost(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        String fileName = req.getParameter("fileName");
        String show = req.getParameter("show");
        InetAddress inetAddress = null;
        try {
            TSDTVEpisode episode = library.getShow(show).getEpisode(fileName);
            inetAddress = InetAddress.getByName(ServletUtils.getIpAddress(req));
            if(!servletBlacklist.contains(inetAddress.toString())) {
                tsdtv.playFromWeb(episode, inetAddress);
            }
        } catch (ShowNotFoundException snfe) {
            resp.sendError(HttpServletResponse.SC_NOT_FOUND, "Could not find file matching show " + show + " and episode " + fileName);
        } catch (StreamLockedException e) {
            resp.sendError(HttpServletResponse.SC_FORBIDDEN, "The stream is currently locked from web access");
        } catch (SurgeProtector.FloodException fe) {
            servletBlacklist.add(inetAddress.toString());
            resp.sendError(HttpServletResponse.SC_FORBIDDEN, "Flood detected. Calm down man");
        } catch (EpisodeAlreadyQueuedException e) {
            resp.sendError(HttpServletResponse.SC_BAD_REQUEST, "That episode is already in the queue");
        }
    }
}

src/main/resources/webroot/filenames.jsp
<%@taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<html>
    <head>
        <meta http-equiv="Content-Type" CONTENT="text/html;charset=utf-8">
        <title>Filename Database</title>
    </head>
    <body>
    <h1>Official filename database of ${name}</h1>
    <ul>
        <c:forEach items="${filenames}" var="fname" varStatus="fnameIdx">
            <li>
                <a href="${serverUrl}/filenames/${fname.encoded}">${fname.unencoded}</a>
            </li>
        </c:forEach>
    </ul>
    </body>
</html>

src/main/resources/webroot/hustle.jsp
<html>
    <head>
        <meta http-equiv="Content-Type" CONTENT="text/html;charset=utf-8">
        <title>Hustle Report</title>
    </head>
    <body>
        <h1 style="text-align:center">Maybe we should hustle as hard as we hate</h1>
        <div style="text-align: center;">
            <img src="<%=request.getContextPath()%>/hustle/chart"></img>
        </div>
    </body>
</html>

src/main/resources/webroot/status.jsp
<%@taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<html>
    <head>
        <meta http-equiv="Content-Type" CONTENT="text/html;charset=utf-8">
        <title>TSDIRC Status</title>
    </head>
    <body>
        <h1 style="text-align:center">Everything is terrible</h1>
        <p style="font-family: 'Courier New', Courier, monospace">
            <c:forEach items="${stats}" var="stat">
                ${stat.key}: ${stat.value}<br/>
            </c:forEach>
        </p>
    </body>
</html>

src/main/resources/webroot/tsdtv.jsp
<!DOCTYPE html>
<%@taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/functions" prefix="fn" %>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>TSDTV 2.0 rev.D</title>

    <%--favicon--%>
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
    <link rel="icon" href="/favicon.ico" type="image/x-icon">

    <!-- Bootstrap -->
    <link href="css/darkly/bootstrap.min.css" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="js/bootstrap.min.js"></script>
    <script src="js/jquery.bootstrap-growl.min.js"></script>

    <%--video.js--%>
    <link href="//vjs.zencdn.net/4.11/video-js.css" rel="stylesheet">
    <script src="//vjs.zencdn.net/4.11/video.js"></script>

    <script>

        (function update_nowplaying() {
            $.get('/tsdtv/np?type=nowplaying',{},function(responseText) {
                $('#nowplaying').html(responseText).text();
            }).then(function() {
                setTimeout(update_nowplaying, 1000 * 10);
            });
        })();

        (function update_queue() {
            $.get('/tsdtv/np?type=queue',{},function(responseText) {
                $('#queue').html(responseText).text();
            }).then(function() {
                setTimeout(update_queue, 1000 * 10);
            });
        })();

        (function update_blocks() {
            $.get('/tsdtv/np?type=blocks',{},function(responseText) {
                $('#blocks').html(responseText).text();
            }).then(function() {
                setTimeout(update_blocks, 1000 * 60 * 10);
            });
        })();

        (function update_viewers() {
            $.get('/tsdtv/np?type=viewers',{},function(responseText) {
                $('#viewers').html(responseText).text();
            }).then(function() {
                setTimeout(update_viewers, 1000 * 10);
            });
        })();

        $(function() {
            var form = $('.playEpisode');
            $(form).submit(function (event) {
                $.ajax({
                    type: "POST",
                    url: "/tsdtv/play", //process to mail
                    data: $(this).serialize(),
                    success: function (msg) {
                        $('#episodePlayModal').modal('show');
                    },
                    error: function(xhr, status, error) {
                        $.bootstrapGrowl(xhr.responseText, {
                            type: 'danger',
                            width: 'auto',
                            allow_dismiss: true
                        });
                    }
                });
                event.preventDefault();
            });

        });
    </script>
</head>
<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-9">
            <c:choose>
                <c:when test="${not empty param.vlc}">
                    <embed autoplay="yes" target="${directLink}"
                       loop="true" name="VLC"
                       type="application/x-vlc-plugin" volume="100" height="750" width="100%" id="vlc">
                    <a href="/tsdtv">videojs version</a>
                </c:when>
                <c:otherwise>
                    <video id="example_video_1" class="video-js vjs-default-skin"
                           controls loop preload="auto" width="100%" height="750px"
                           poster="http://i.imgur.com/4Q7jsCr.jpg"
                           data-setup='{"autoplay": true}'>
                        <source src="${directLink}" type='${videoFmt}' />
                        <p class="vjs-no-js">To view this video please enable JavaScript, and consider upgrading to a web browser that <a href="http://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a></p>
                    </video>
                    <a href="/tsdtv?vlc=yes">VLC version</a>
                </c:otherwise>
            </c:choose>
        </div>
        <div class="col-md-3">

            <%--Collection of right-hand tabs--%>
            <div role="tabpanel">

                <!-- Nav tabs -->
                <ul class="nav nav-tabs nav-justified" role="tablist">
                    <li role="presentation" class="active"><a href="#schedule" aria-controls="schedule" role="tab" data-toggle="tab">Schedule</a></li>
                    <li role="presentation"><a href="#catalogTab" aria-controls="catalogTab" role="tab" data-toggle="tab">Catalog</a></li>
                    <li role="presentation"><a href="#chat" aria-controls="chat" role="tab" data-toggle="tab">Chat</a></li>
                </ul>

                <!-- Tab panes -->
                <div class="tab-content">

                    <%--Schedule--%>
                    <div role="tabpanel" class="tab-pane active" id="schedule">

                        <%--now playing--%>
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <h3 class="panel-title" style="color: #00bc7e"><strong>NOW PLAYING</strong></h3>
                            </div>
                            <div class="panel-body">
                                <div id="nowplaying">Loading...</div>
                            </div>
                        </div>

                        <%--next in the queue--%>
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <h3 class="panel-title" style="color: #00bc7e">Up next</h3>
                            </div>
                            <div class="panel-body">
                                <div id="queue">Loading...</div>
                            </div>
                        </div>

                        <%--blocks that will play later today--%>
                        <div id="blocks">Loading...</div>

                    </div>

                    <%--Catalog--%>
                    <div role="tabpanel" class="tab-pane" id="catalogTab" style="max-height: 700px; overflow-y: scroll;">
                        <div class="panel-group" id="catalog" role="tablist" aria-multiselectable="true">
                            <c:forEach items="${catalog}" var="show" varStatus="showIdx">
                                <%--Show--%>
                                <c:set var="expand" value="${showIdx.first}"/>
                                <div class="panel panel-default">
                                    <div class="panel-heading" role="tab" id="<c:out value="${show.key.rawName}"/>-head">
                                        <h4 class="panel-title">
                                            <a ${expand ? '' : 'class="collapsed"'} data-toggle="collapse" data-parent="#catalog" href="#<c:out value="${show.key.rawName}"/>-content" aria-expanded="${expand}" aria-controls="<c:out value="${show.key.rawName}"/>-content">
                                                <c:out value="${show.key.prettyName}"/>
                                            </a>
                                        </h4>
                                    </div>
                                    <div id="<c:out value="${show.key.rawName}"/>-content" class="panel-collapse collapse" role="tabpanel" aria-labelledby="<c:out value="${show.key.rawName}"/>-head">
                                        <div class="panel-body">
                                            <ul class="list-group">
                                                <c:forEach items="${show.value}" var="episode">
                                                    <%--Episode--%>
                                                    <li class="list-group-item">
                                                        <c:out value="${episode.prettyName}"/>
                                                        <form class="playEpisode" name="playEpisode">
                                                            <input type="hidden" name="fileName" value="${episode.rawName}">
                                                            <input type="hidden" name="show" value="${show.key.rawName}">
                                                            <input class="btn btn-sm btn-success" type="submit" value="Play" >
                                                        </form>
                                                    </li>
                                                </c:forEach>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            </c:forEach>
                        </div>
                    </div>

                    <%--Chat ;^)--%>
                    <div role="tabpanel" class="tab-pane" id="chat">;^)</div>

                </div>

            </div>
            <div>
                Viewers: <span id="viewers" class="badge">...</span>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="episodePlayModal" tabindex="-1" role="dialog" aria-labelledby="episodePlayModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="episodePlayModalLabel">You did it!</h4>
            </div>
            <div class="modal-body">
                Your show has been enqueued :^)
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="controlModal" tabindex="-1" role="dialog" aria-labelledby="control-modal-label" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="control-modal-label">Nothing...</h4>
            </div>
            <div id="control-modal-body" class="modal-body">
                Nothing...
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
</body>
</html>